### PR TITLE
Fix formatting over entire repo

### PR DESCRIPTION
**Pull request by CCInc**
With the addition of precommit-ci, the entire library needs to be formatted back to a good baseline for future PRs.

### CODE REVIEW

**Review by nicolas-chaulet — APPROVED** [review]
Looks great thanks! Some tests are failing though, I am assuming it is due to mypy being on a newer version or something, would you be able to address that?

**Comment by CCInc** [comment]
Ok, got that fixed. Any thoughts on "Generate requirements.txt"? Should we leave that in or remove it from the precommit?

**Comment by nicolas-chaulet** [comment]
If it fails because requirements.txt is out of date then it's a good thing, the user should update the requirements.txt based on the poetry lock file (there is a command for that if not using pre-commit)

**Comment by CCInc** [comment]
The issue is that it will always fail, because pre-commit.ci doesn't have poetry on their machine. I tried adding it but haven't had any luck. 
image

**Comment by nicolas-chaulet** [comment]
Let's leave it as is then!

**Pull request merged**
